config/routes.rb
Rails.application.routes.draw do
  root to: 'destinations#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :destinations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :date, presence: true
  validates :first_name, presence: true
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def index
    @destinations = Destination.all
  end

  def show
    @destination = Destination.find(params[:id])
  end

  def new
    @destination = Destination.new
  end

  def create
    @destination = Destination.new(destination_params)
    @destination.save
    redirect_to destination_path(@destination)
  end

  private

  def destination_params
    params.require(:destination).permit(:name, :description, :location, :date, :first_name, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/destinations/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://images.unsplash.com/photo-1474433188271-d3f339f41911?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://images.unsplash.com/photo-1519046904884-53103b34b206?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80" class="d-block w-100" alt="...">
    </div>
  </div>

    <!--Caption-->
      <div class="carousel-caption">
        <div class="animated fadeInDown">
           <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="heading-font">Favourite Travel Destinations</h1>
        <%= link_to "Add yours", new_destination_path(@destination), :class => "btn btn-danger" %>
      </div>
    </div>
  </div>
        </div>
      </div>
      <!--Caption-->
    </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#panel").delay(3000).slideDown();
    $("#panel2").delay(6000).slideDown();
  });

</script>



<style>
#panel, #flip, #panel2 {
  padding: 5px;
  text-align: center;
}

#panel, #panel2 {
  padding: 50px;
  display: none;
}
</style>
</head>
<body>
  <main class='main'>
    <section class='left section'>
      <div class="video-responsive">
        <iframe width="420" height="315" src="https://www.youtube.com/embed/Zn9APBq5aHU" frameborder="0" allowfullscreen></iframe>
      </div>
    </section>
    <section class="right section">
      <div id="panel"><h2><strong>Kos, Greece</strong></h2>
        <p>Kos, one of the Greek Dodecanese islands is known for it's splendid beaches, palm trees, active nightlife with amazing hotels by the sea and so much to do!</p>
        <p>There are many restaurants with appetizing Greek cuisine right by the ocean where you can soak up the stunning views and some hotels have their own private beach areas in which you can sunbathe at your own leisure.</p>
        <p>The island is located within a stone's throw from Bodrum, Turkey. Only a 45 minute ferry away, why not mix your trip and add a Turkish flavour to it!</p>
        <p>The video provides a snippet of Kos, is it enough to tempt you to go one day? I think so!</p>
      </div>
    </section>
  </main>

<h1 class="heading"><strong>Favourite Destinations</strong></h1>
<div class="content d-flex">
  <div class="cards">
<% @destinations.each do |destination| %>
  <div class="card-cocktail" style="background-image: url( <%= cl_image_path destination.photo.key %>)">

  <h2><%= link_to "#{destination.name}", destination_path(destination), class: "card-link" %></h2>
 </div>
<% end %>
</div>
</div>

<main class='main'>
    <section class='left section'>
      <div class="video-responsive">
        <iframe width="420" height="315" src="https://www.youtube.com/embed/fLRMvUGqEUs" frameborder="0" allowfullscreen></iframe>
    </section>
      <section class="right section">
    <div id="panel2"><h2><strong>Waiheke Island, New Zealand</strong></h2>
      <p>Waiheke Island is one of the largest islands in the Hauraki Gulf of New Zealand. It boasts amazing wineyards, picturesque beaches and a range of activities to enjoy if you fancy!</p>
      <p>It is a 40 minute ferry ride from downtown Auckland and is easy to get around the island by car, public transport or by booking tours.</p>
      <p>On the island you can try the great coffee on offer or have a taste of New Zealand's fresh cuisine.</p>
      <p>Due to it's picturesque views the island is the perfect setting for weddings and honeymoons. Peak at the video and you'll see why this island is worth visiting.</p>
    </div>
  </section>
</main>

<div class="footer">
  <i class="fab fa-facebook"></i>
  <i class="fab fa-twitter-square"></i>
  <i class="fab fa-instagram"></i>
  <p>Amazing destinations for enjoyable times</p>
</div>

app/views/destinations/new.html.erb
<div class="banner" style="background-image: url(https://images.unsplash.com/photo-1469474968028-56623f02e42e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1053&q=80);">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6 col-md-7 my-5">
        <div class="card" style="width: 28rem, height: 18rem;">
          <div class="search-form box-shadow p-4">
            <div class="text-center">
            <h1 class="cocktail-name">Add a Destination</h1>
            </div>
            <%= simple_form_for(@destination) do |f| %>
            <%= f.input :name %>
            <%= f.input :photo, as: :file %>
            <%= f.input :location %>
            <%= f.input :date %>
            <%= f.input :description %>
            <%= f.input :first_name %>
            <div class="text-center">
            <%= f.submit "Add Destination", class: "btn btn-danger" %>
          </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/destinations/show.html.erb
<i class="fas fa-globe-europe"><%= link_to "Travel Destinations", destinations_path(@destination), class: "btn btn-danger" %></i>
<div class="banner2" style="background-image: url(https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2853&q=80);">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6 col-md-6 col-sm-2 my-4 p-1">
        <div class="card2 py-2 mt-5 px-3 mr-3">
          <div class="text-center">
            <h2><%= @destination.name %></h2>
            <div>
              <%= cl_image_tag @destination.photo.key, height: 300, width: 400, crop: :fill%>
            </div>
          </div>
            <div class="text-center">
              <p><strong>Location: </strong><%= @destination.location %></p>
              <p><strong>Date of visit: </strong> <%= @destination.date.strftime('%d-%m-%Y') %></p>
              <p><strong>Description: </strong> <%= @destination.description %></p>
              <p><strong>First Name: </strong> <%= @destination.first_name %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>